---
title: "Analisis Sentimen Hotel di TrpAdvisor"
author: "Siti Mardhiyah/123180101 & Farisa Yumna P.HP/123180103"
date: "1/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(dplyr)
library(tm)
library(wordcloud)
library(syuzhet) #untuk membaca fungsi get_nrc
library(ggplot2)
library(e1071) #untuk naive bayes
library(caret) #untuk klasifikasi data
library(RTextTools)
library(shiny)
```

```{r}
#import dataset
hotel <- read.csv(here("tripadvisor_hotel_reviews.csv"))
View(hotel)
#konversi data ke text
hotelText <- Corpus(VectorSource(hotel$Review))
hotelText
inspect(hotelText[1:5])
```

```{r}
#cleaning
dataclean<- hotelText %>%
  tm_map(content_transformer(tolower)) %>%
  tm_map(removePunctuation) %>%
  tm_map(removeNumbers) %>%
  tm_map(removeWords, stopwords(kind = "en")) %>%
  tm_map(stripWhitespace)
databersih <- data.frame(text = unlist(sapply(dataclean, '[')), stringsAsFactors = FALSE)
View(databersih)
write.csv(databersih, file = "reviewclean.csv")
```

```{r}
#Sentimen 
review <- as.character(databersih$text)
get_nrc_sentiment('happy')
get_nrc_sentiment('excitement')
review_nrc <- get_nrc_sentiment(review)

review_combine <- cbind(databersih$text, review_nrc)
par(mar=rep(3,4))
barplot1 <- barplot(colSums(review_nrc), col = rainbow(10), ylab = 'count', main = 'sentiment analisis')
#barplot2 <- barplot1
```

```{r}
#
df <- read.csv("reviewclean.csv",stringsAsFactors = F)
View(df)
glimpse(df)
#mengacak urutan
set.seed(20)
df <- df[sample(nrow(df)),]
glimpse(df)
corpus <- Corpus(VectorSource(df$text))
```

```{r}
corpus.clean <- corpus %>%
  tm_map(content_transformer(tolower)) %>%
  tm_map(removePunctuation) %>%
  tm_map(removeNumbers) %>%
  tm_map(removeWords, stopwords(kind = "en")) %>%
  tm_map(stripWhitespace)
dtm <- DocumentTermMatrix(corpus.clean)
corpus.clean
inspect(dtm[1:10,1:10])
inspect(corpus.clean[1:3])
```

```{r}
df.train <- df$text[1:1000]
df.test <- df$text[1001:2000]

dtm.train <- dtm[1:1000,]
dtm.test <- dtm[1001:2000,]

corpus.clean.train <- corpus.clean[1:1000]
corpus.clean.test <- corpus.clean[1001:2000]

dim(dtm.train)
fivefreq <- findFreqTerms(dtm.train, 5)
fivefreq
length(fivefreq)

dtm.train.nb <- DocumentTermMatrix(corpus.clean.train, control = list(dictionary = fivefreq))
dtm.test.nb <- DocumentTermMatrix(corpus.clean.test, control = list(dictionary = fivefreq))

dim(dtm.test.nb)
convert_count <- function(x){
  y <- ifelse(x>0,1,0)
  y <- factor(y,levels = c(0,1), labels = c("no","yes"))
  head(y)
}

trainNB <- apply(dtm.train.nb, 2, convert_count)
testNB <- apply(dtm.test.nb, 1, convert_count)

```

```{r}
wordcloud(corpus.clean, min.freq = 4, max.words = 100, random.order = F, colors = brewer.pal(8, "Dark2"))
```

```{r}
#SERVER
server <- function(input, output){
  #output data
  output$tbl = DT::renderDataTable({
    DT::datatable(review_hotel, options = list(lengthChange = FALSE))
  })
  #Output Scatterplot
  output$scatterplot <- renderPlot({review_dataset <- read.csv("reviewclean.csv",stringsAsFactors = F)
  
  review <- as.character(review_dataset$text)
  get_nrc_sentiment('happy')
  get_nrc_sentiment('excitement')
  review_nrc <- get_nrc_sentiment(review)
  
  review_combine <- cbind(databersih$text, review_nrc)
  par(mar=rep(3,4))
  barplot1 <- barplot(colSums(review_nrc), col = rainbow(10), ylab = 'count', main = 'sentiment analisis')}, height = 400)
  
  #Output wordcloud
  df <- read.csv("reviewclean.csv",stringsAsFactors = F)
  output$Wordcloud <- renderPlot({
    set.seed(20)
    df <- df[sample(nrow(df)),]
    glimpse(df)
    
    corpus <- Corpus(VectorSource(df$text))
    
    inspect(corpus[1:5])
    
    #untuk membersihkan data2 yang tidak berguna
    corpus.clean <- corpus %>%
      tm_map(content_transformer(tolower)) %>%
      tm_map(removePunctuation) %>%
      tm_map(removeNumbers) %>%
      tm_map(removeWords, stopwords(kind = "en")) %>%
      tm_map(stripWhitespace)
    dtm <- DocumentTermMatrix(corpus.clean)
    
    inspect(dtm[1:10,1:20])
   
    df.train <- df$text[1:1000]
    df.test <- df$text[1001:2000]
    
    dtm.train <- dtm[1:1000,]
    dtm.test <- dtm[1001:2000,]
    
    corpus.clean.train <- corpus.clean[1:1000]
    corpus.clean.test <- corpus.clean[1001:2000]
    
    dim(dtm.train)
    fivefreq <- findFreqTerms(dtm.train, 5)
    fivefreq
    length(fivefreq)
    
    dtm.train.nb <- DocumentTermMatrix(corpus.clean.train, control = list(dictionary = fivefreq))
    dtm.test.nb <- DocumentTermMatrix(corpus.clean.test, control = list(dictionary = fivefreq))
    
    dim(dtm.test.nb)
    convert_count <- function(x){
      y <- ifelse(x>0,1,0)
      y <- factor(y,levels = c(0,1), labels = c("no","yes"))
      y
    }
    
    trainNB <- apply(dtm.train.nb, 2, convert_count)
    testNB <- apply(dtm.test.nb, 1, convert_count)
    
    wordcloud(corpus.clean, min.freq = 4, max.words = 100, random.order = F, colors = brewer.pal(8, "Dark2"))
  })
}
```

```{r}
review_hotel <- read.csv("reviewclean.csv")
a <- review_hotel$text
ui <- fluidPage(
  titlePanel("Analisis Sentimen Hotel di TripAdvisor"),
  mainPanel(
    tabsetPanel(type = "tabs",
                tabPanel("Dataset Review Hotel", DT::dataTableOutput('tbl')),
                tabPanel("Scatterplot", plotOutput("scatterplot")),
                tabPanel("Wordcloud", plotOutput("Wordcloud"))
                )
  )
)

shinyApp(ui = ui, server = server)
```

```{r}
# Build a term-document matrix
TextDoc_dtm <- TermDocumentMatrix(dataclean)
dtm_m <- as.matrix(TextDoc_dtm)
# Sort by descearing value of frequency
dtm_v <- sort(rowSums(dtm_m),decreasing=TRUE)
dtm_d <- data.frame(word = names(dtm_v),freq=dtm_v)
# Display the top 5 most frequent words
head(dtm_d, 5)

barplot(dtm_d[1:5,]$freq, las = 2, names.arg = dtm_d[1:5,]$word,
        col ="lightgreen", main ="Top 5 most frequent words",
        ylab = "Word frequencies")

#generate word cloud
set.seed(1234)
wordcloud(words = dtm_d$word, freq = dtm_d$freq, min.freq = 5,
          max.words=100, random.order=FALSE, rot.per=0.40, 
          colors=brewer.pal(8, "Dark2"))
```